#!/usr/bin/env node

const dict = {
	"い": 1,
	"いっ": 1,
	"いー": 1,
	"いち": 1,
	"いん": 1,
	// "いつ": 5,
	"お": 0,
	"おお": 0,
	"おう": 0,
	"おん": 0,
	"きゅう": 9,
	"きゅー": 9,
	"く": 9,
	"ぐ": 9,
	"こ": 5,
	"こう": 5,
	"こー": 5,
	"ご": 5,
	"ごう": 5,
	"ごー": 5,
	"さ": 3,
	"さー": 3,
	"さっ": 3,
	"さん": 3,
	"ざ": 3,
	"ざー": 3,
	"ざっ": 3,
	"ざん": 3,
	"し": 4,
	"しー": 4,
	"しっ": 4,
	"しょ": 4,
	"しん": 4,
	"じ": 4,
	"じー": 4,
	"じっ": 4,
	"じん": 4,
	"じゅう": 1,
	"じゅー": 1,
	"じょ": 4,
	"つ": 2,
	"てん": 10,
	"と": 10,
	"とっ": 10,
	"とう": 10,
	"とお": 10,
	"とー": 10,
	"ど": 10,
	"どっ": 10,
	"どう": 10,
	"どー": 10,
	"な": 7,
	"なっ": 7,
	"なな": 7,
	"なん": 7,
	"に": 2,
	"にー": 2,
	"にい": 2,
	"にっ": 2,
	"にん": 2,
	"は": 8,
	"はー": 8,
	"はっ": 8,
	"ぱ": 8,
	"ぱー": 8,
	"ぱっ": 8,
	"ぱん": 8,
	"ば": 8,
	"ばー": 8,
	"ばん": 8,
	"ひ": 1,
	"ひと": 1,
	"びと": 1,
	"ふ": 2,
	"ぷ": 2,
	"ぶ": 2,
	"ま": 0,
	"み": 3,
	"みー": 3,
	"みい": 3,
	"みっ": 3,
	"みつ": 3,
	"みん": 3,
	"む": 6,
	"や": 8,
	"やっ": 8,
	"やー": 8,
	"よ": 4,
	"よっ": 4,
	"よん": 4,
	"る": 6,
	"れ": 0,
	"れい": 0,
	"れー": 0,
	"れん": 0,
	"ろ": 6,
	"ろう": 6,
	"ろー": 6,
	"ろっ": 6,
	"ろく": 6,
	"わ": 8,
	"わー": 8,
	"を": 0,
	"ん": 0,
	"ー": 0,
};

var args = process.argv.slice(2);
// console.log(args);

if(args.length < 1 || args[0] == '-h' || args[0] == '--help'){
	console.error("Usage: kana2nums [hiragana]");
	process.exit(1);
}

var kana = args[0];
var is_ignore = false;
var is_strict = false;
// console.log(kana);

if(args[0] == '-ignore' || args[0] == '--ignore'){
	kana = args[1];
	is_ignore = true;
}else if(args[1] == '-ignore' || args[1] == '--ignore'){
	kana = args[0];
	is_ignore = true;
}else if(args[0] == '-strict' || args[0] == '--strict'){
	kana = args[1];
	is_strict = true;
}else if(args[1] == '-strict' || args[1] == '--strict'){
	kana = args[0];
	is_strict = true;
}

var out = "";
var s_prev = "";
var s = kana;
var succeeded = false;
var index = 0;

while(true){
	s_prev = s.slice(0);

	// console.log(s);

	if(s.length >= 3){
		var c = s.slice(0, 3);
		if(dict.hasOwnProperty(c)){
			out += dict[c];
			s = s.slice(3);
			index += 3;
			continue;
		}
	}

	if(s.length >= 2){
		var c = s.slice(0, 2);
		if(dict.hasOwnProperty(c)){
			out += dict[c];
			s = s.slice(2);
			index += 2;
			continue;
		}
	}
	
	if(s.length >= 1){
		var c = s[0];
		if(dict.hasOwnProperty(c)){
			out += dict[c];
			s = s.slice(1);
			index += 1;
		}
	}

	if(s.length == 0){
		succeeded = true;
		break;
	}else if(is_ignore === true && s == s_prev){
		s = s.slice(1);
		index += 1;
		continue;
	}else if(is_ignore === false && s == s_prev){
		break;
	}
}

if(succeeded){
	console.log(out);
}else{
  if(is_strict){
    process.exit(1);
  }else{
    console.log(out);
    console.error( "[エラー] " + (index+1) + "文字目("+s[0]+")が翻訳できませんでした。" );
    process.exit(1);
  }
}
